apiVersion: v1
kind: Service              
metadata:
  name: jupyter-notebook-service
spec:
  type: LoadBalancer       
  ports:
  - port: 8888               
    protocol: TCP          
    targetPort: 8888         
  selector:                
    app: jupyter-notebook       