apiVersion: v1
kind: Service              
metadata:
  name: spark-service
spec:
  type: LoadBalancer       
  ports:
  - port: 8080               
    protocol: TCP          
    targetPort: 8080         
  selector:                
    app: spark-service      